# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda2d9ec3ec22444502e18bf22575f8a7acc25902e7dbd7317f150fefaca51b7fbb5069ccbbe9dd224a9cd73cc915e9eb322b5e26a37c0ed6b900785861d36ab

test:
  secret_key_base: 706244e5978ffd5b50cff3cf872cb699267172ce7d825fb394ea5144fea68fbcf8114fbfa78009ffd450e3a0af8353cd65f8d8d39ed3913239b64a491204a052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
